[package]
name = "rauncher"
version = "0.1.0"
authors = ["devilune <devlune@gmail.com>"]
edition = "2018"

[dependencies]

[dependencies.gtk]
version = "0.7.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]